-- Seed de instructores para Supabase
-- Basado en la lista provista por el usuario.
-- Nota: el campo correo_electronico se guarda como texto para mantener el valor original.
-- Si necesitas múltiples correos normalizados, conviene separarlos en otra tabla.

insert into public.instructores (id, nombre_completo, usuario, correo_electronico) values
  (6, 'DAVID SANTIAGO ZEA CARVAJAL', 'DAVID ZEA', 'davidsantiagozeacarvajal@gmail.com'),
  (7, 'YENNI CAROLINA GARCIA OCHOA', 'YENNI GARCIA', 'yennicgarcia@gmail.com'),
  (8, 'YOBANA GARCIA CANDELA', 'YOBANA GARCIA', 'ygarciac1110@gmail.com'),
  (9, 'ELSA MILENA SOSA ROMERO', 'ELSA SOSA', 'elmisosro1@hotmail.com'),
  (10, 'ISABEL CRISTINA BARRERO NIÑO', 'ISABEL BARRERO', 'arte1959icbn@gmail.com'),
  (11, 'MERY PAEZ PINEDA', 'MERY PAEZ', 'merycrismes23@hotmail.com'),
  (12, 'LUZ MARINA NOVOA ORTIZ', 'LUZ NOVOA', 'novoa958@gmail.com'),
  (13, 'NESTOR ENRIQUE GOMEZ RUIZ', 'NESTOR GOMEZ', 'enriquegomez889@hotmail.com'),
  (14, 'LOLITA MADELEINE CROCKER DE LA MOTTA', 'LOLITA CROCKER', 'accionlegalmac.sas@gmail.com / madeleinecrockerdelamotta@hotmail.com'),
  (15, 'LINA MARCELA JIMENEZ ARANGO', 'LINA JIMENEZ', 'lina.asesoralegal@gmail.com'),
  (16, 'EDWAR MAURICIO PERDOMO', 'EDWAR PERDOMO', 'edwarm3@yahoo.es'),
  (17, 'YEISON IVAN BARRERA CORREDOR', 'YEISON BARRERA', 'yeisonbarrera1420@gmail.com'),
  (18, 'YULY ANDREA ZAPATA RODRIGUEZ', 'YULY ZAPATA', 'yulyzapata089@gmail.com / yazapatar@unal.edu.co'),
  (19, 'EDNA KATHERINE RIVAS VELASQUEZ', 'EDNA RIVAS', 'catdogsoacha@gmail.com'),
  (20, 'JAIRO ESTEBAN RAMIREZ CASAS', 'JAIRO RAMIREZ', 'jairoesteban2018@gmail.com / valentinacastell2000@gmail.com'),
  (21, 'JUAN ALEXANDER PINZON CONTRERAS', 'JUAN PINZON', 'juanalexanderpinzon1@gmail.com'),
  (22, 'ALBA JAZMIN PABON PEÑA', 'ALBA PABON', 'ajpabon8@gmail.com'),
  (23, 'YENNY ALEJANDRA TORRES BURGOS', 'YENNY TORRES', 'yatorresb@udistrital.edu.co'),
  (24, 'DANIEL ANDRES FONSECA CARREÑO', 'DANIEL FONSECA', 'focads13@gmail.com'),
  (25, 'FRANK ALEXIS SOLORZANO CAMACHO', 'FRANK SOLORZANO', 'franksolorzano01@gmail.com'),
  (26, 'LUIS FERNANDO HERNANDEZ', 'LUIS HERNANDEZ', 'lfernando1982@gmail.com'),
  (27, 'LUZ ANGELA TRUJILLO', 'LUZ TRUJILLO', 'latrujillo2023@gmail.com / luzangela.trujillo34@gmail.com'),
  (28, 'SONIA MARCELA PELAEZ THOMPSON', 'SONIA PELAEZ', 'sonipelaez0912@gmail.com'),
  (29, 'LUCIA ESPERANZA CARRILLO ROJAS', 'LUCIA CARRILLO', 'luciaesperanzacarrillorojas@gmail.com'),
  (30, 'PEDRO PABLO MARTINEZ SILVA', 'PEDRO MARTINEZ', 'pedromartinez72@gmail.com / ppmartinez68@misena.edu.co'),
  (31, 'ANDRES FELIPE GUARNIZO VARGAS', 'ANDRES GUARNIZO', 'andresguarnizo26@gmail.com'),
  (32, 'ARGENIZ BELLO BELLO', 'ARGENIZ BELLO', 'argenizbello@yahoo.com.ar'),
  (33, 'EDUARDO RAMIREZ DIAZ', 'EDUARDO RAMIREZ', 'erd10002@hotmail.com'),
  (34, 'LEIDY VIVIANA CASALLAS TORRES', 'LEIDY CASALLAS', 'viviana_casallas150@hotmail.com / viviana.casallas86@gmail.com'),
  (35, 'LEONARDO VELASQUEZ CASTAÑEDA', 'LEONARDO VELASQUEZ', 'leovelaca@gmail.com'),
  (36, 'LINA MARCELA CANO POLO', 'LINA CANO', 'lincano2002@gmail.com'),
  (37, 'DIEGO ARMANDO OSPINA TOVAR', 'DIEGO OSPINA', 'diego.ospinatovar@gmail.com'),
  (38, 'HUGO ALDEMAR DE CASTRO HERRERA', 'HUGO CASTRO', 'hadecastroh@gmail.com'),
  (39, 'JHON JAIRO REINA GARZON', 'JHON REINA', 'jhonjairoreinaing4@gmail.com'),
  (40, 'GABRIELA HERNANDEZ ORTIZ', 'GABRIELA HERNANDEZ', '19980718gho@gmail.com'),
  (41, 'MARISOL MALDONADO ROSAS', 'MARISOL MALDONADO', 'marisun2023@gmail.com'),
  (42, 'JOHN EDWIN ALAYON BARRENECHE', 'JOHN ALAYON', 'johneab@hotmail.com'),
  (43, 'JUAN MANUEL COMETA BELLO', 'JUAN COMETA', 'juancometabello554@gmail.com'),
  (44, 'FLOR MARIA DEL PILAR SEGURA BALLESTEROS', 'FLOR SEGURA', 'segurapilar73@hotmail.com'),
  (45, 'WILLIAM VALENCIA CARVAJAL', 'WILLIAM VALENCIA', 'williamvalenciacarvajal@gmail.com / wivacar123@gmail.com'),
  (46, 'DORIS AMINTA MORA GUTIERREZ', 'DORIS MORA', 'dorisamintamora@hotmail.com'),
  (47, 'MARIA ALEJANDRA RUBIANO GONZALEZ', 'MARIA RUBIANO', 'maleja.r.gonzalez@gmail.com'),
  (48, 'JOSE WILSON SABOGAL VELASQUEZ', 'JOSE SABOGAL', 'jwsabogalv@gmail.com / jowilsa007@gmail.com'),
  (49, 'JORGE OSWALDO GAMBOA ROJAS', 'JORGE GAMBOA', 'gamba-02@hotmail.com'),
  (50, 'LEIDY MARCELA DIAZ BURITICA', 'LEIDY DIAZ', 'marceladiazburitica@gmail.com'),
  (51, 'LUISA DANIELA MAYORGA MOSCOSO', 'LUISA MAYORGA', 'daniela05_06@hotmail.com'),
  (52, 'ADRIANA TORRES ALVARADO', 'ADRIANA TORRES', 'senaadrianat1@gmail.com / altonivelconsultoria1@gmail.com'),
  (53, 'CAROLINA HERNANDEZ GONZALEZ', 'CAROLINA HERNANDEZ', 'karolina_hergonzalez@hotmail.com / karolina.hergonzalez@gmail.com'),
  (54, 'LUIS GERMAN TORRES OSPINA', 'LUIS TORRES', 'luisgermantorresospina1234@gmail.com'),
  (55, 'PIER PAOLO OVIEDO DUSSAN', 'PIER OVIEDO', 'profepier@gmail.com'),
  (56, 'ANDREA DEL PILAR RODRIGUEZ SALAMANCA', 'ANDREA RODRIGUEZ', 'andreadelpilarrs@gmail.com'),
  (57, 'LEIDY VANESSA MORENO URQUIJO', 'LEIDY MORENO', 'lvane31@hotmail.com'),
  (58, 'BEATRIZ ALCIRA QUIÑONES RAMOS', 'BEATRIZ QUIÑONES', 'alcira0000@gmail.com'),
  (59, 'LUZ HELENA QUINTANA', 'LUZ QUINTANA', 'luzhequi@gmail.com'),
  (60, 'JACKELIN ANDREA ESCOBAR GUZMAN', 'JACKELIN ESCOBAR', 'jackyand2@hotmail.com'),
  (61, 'VALERIA AVILA SEGURA', 'VALERIA AVILA', 'avilaseguravaleria5@gmail.com'),
  (62, 'JUAN CAMILO SANTAMARIA CASTILLO', 'JUAN SANTAMARIA', 'juancacasti1@hotmail.com'),
  (63, 'FREDY OSCAR CAMACHO GONZALEZ', 'FREDY CAMACHO', 'fredyocg1a@gmail.com'),
  (64, 'FRANCISCO ELADIO RAMIREZ ANDRADE', 'FRANCISCO RAMIREZ', 'socupacional1072@hotmail.com'),
  (65, 'ALEXANDER ALEXANDER TORRES TORRES', 'ALEXANDER TORRES', 'alcharris4478@gmail.com'),
  (66, 'DANIEL ARANDIA LEYVA', 'DANIEL ARANDIA', 'danieljuez07@yahoo.com'),
  (67, 'JOSE HERNANDO ANGEL', 'JOSE ANGEL', 'hahernandoangel@gmail.com'),
  (68, 'RAFAEL ALBERTO QUIÑONES LARA', 'RAFAEL QUIÑONES', 'rafael041076@hotmail.com'),
  (69, 'SHAROL VANESSA RODRIGUEZ MATIZ', 'SHAROL RODRIGUEZ', 'svanessa.rodriguez28@gmail.com'),
  (70, 'LAURA CAROLINA ALVARADO CORDOBA', 'LAURA ALVARADO', 'lauritacac27@gmail.com'),
  (71, 'JOICE PAOLA OSPINA MURILLO', 'JOICE OSPINA', 'joiceospina@gmail.com'),
  (72, 'JONATAN TOVAR ALMANZA', 'JONATAN TOVAR', 'jtovaralmanza21@gmail.com'),
  (73, 'OSCAR ARMANDO GUTIERREZ BERNAL', 'OSCAR GUTIERREZ', 'oscargso@yahoo.es'),
  (74, 'JEINNY SULFEY PEÑA AMADOR', 'JEINNY PEÑA', 'jeinsul@hotmail.com')
on conflict (id) do update set
  nombre_completo = excluded.nombre_completo,
  usuario = excluded.usuario,
  correo_electronico = excluded.correo_electronico,
  activo = true;
