-- Supabase schema for the planeador integration
-- Based on the tables shown in the schema visualizer:
-- programa, competencia, programa_competencia, instructores

create table if not exists public.programa (
  codigo_programa bigint primary key,
  version_programa integer,
  nombre_programa varchar not null
);

create table if not exists public.competencia (
  codigo_competencia integer primary key,
  denominacion_competencia varchar not null
);

create table if not exists public.programa_competencia (
  codigo_programa bigint not null references public.programa (codigo_programa) on update cascade on delete cascade,
  codigo_competencia integer not null references public.competencia (codigo_competencia) on update cascade on delete cascade,
  duracion_horas integer not null,
  primary key (codigo_programa, codigo_competencia)
);

create table if not exists public.instructores (
  id bigint generated by default as identity primary key,
  nombre_completo text not null,
  usuario text not null,
  correo_electronico text,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_programa_nombre on public.programa (nombre_programa);
create index if not exists idx_programa_competencia_programa on public.programa_competencia (codigo_programa);
create index if not exists idx_programa_competencia_competencia on public.programa_competencia (codigo_competencia);
create index if not exists idx_instructores_usuario on public.instructores (usuario);
create index if not exists idx_instructores_nombre on public.instructores (nombre_completo);
create index if not exists idx_instructores_correo on public.instructores (correo_electronico);

-- Helper view for login/search flows by usuario, nombre or correo
create or replace view public.v_instructores_acceso as
select
  id,
  nombre_completo,
  usuario,
  correo_electronico,
  activo,
  created_at
from public.instructores
where activo = true;

create or replace function public.buscar_instructor_acceso(termino text)
returns setof public.v_instructores_acceso
language sql
stable
as $$
  select *
  from public.v_instructores_acceso
  where lower(usuario) like '%' || lower(trim(termino)) || '%'
     or lower(nombre_completo) like '%' || lower(trim(termino)) || '%'
     or lower(coalesce(correo_electronico, '')) like '%' || lower(trim(termino)) || '%'
  order by nombre_completo;
$$;

-- Optional view to make frontend lookups easier
create or replace view public.v_programa_competencia_detalle as
select
  pc.codigo_programa,
  p.nombre_programa,
  pc.codigo_competencia,
  c.denominacion_competencia,
  pc.duracion_horas
from public.programa_competencia pc
join public.programa p on p.codigo_programa = pc.codigo_programa
join public.competencia c on c.codigo_competencia = pc.codigo_competencia;
